import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Link from "next/link";
import { Github, Home, LayoutDashboard, FolderGit2 } from "lucide-react";
import { Bricolage_Grotesque } from "next/font/google";
import { Button } from "@/components/ui/button";

const font = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata = {
  title: "YetiCodes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen  ${font.className}`}>
        <nav className="fixed top-0 left-0 right-0 z-50 bg-background border-b border-border/40 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-16 items-center mx-auto px-5">
            <Link href="/" className="flex items-center space-x-2">
              <Github className="h-6 w-6" />
              <span className="font-bold">DevAI</span>
            </Link>
            <div className="flex items-center space-x-4 ml-auto">
              <Link href="/">
                <Button variant="ghost" size="sm">
                  <Home className="h-4 w-4 mr-2" />
                  Home
                </Button>
              </Link>

              <Link href="/dashboard">
                <Button variant="ghost" size="sm">
                  <FolderGit2 className="h-4 w-4 mr-2" />
                  Your Projects
                </Button>
              </Link>
            </div>
          </div>
        </nav>
        <NuqsAdapter>
          <main className="container pt-16 mx-auto">{children}</main>
        </NuqsAdapter>
      </body>
    </html>
  );
}
